---
exclude: inputs/.*
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--filter-files, --line-length, '100', --profile, black]
        files: \.py$
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
        args: [--line-length, '100']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.8
        args: [--max-line-length=100]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: pipenv run mypy
        language: system
        types: [python]
        args: [--show-traceback]
